version: "3.8"
services:
  postgres:
    image: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./.env
    
  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - postgres

volumes:
  data:
